### ISSUE TITLE
Add very basic tests

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/cloud-functions-gmail-nodejs#10]
This code is out there in the wild on a blog post.  At a very minimum, we need to keep update dependencies so it works for new folks.  I enabled renovate on the repo, but to have any confidence in the updates, we need some basic tests to make sure we don't break it :)

**Comment by lenyabloko** [comment]
Thanks, Justin for your help!

The blog does explain that "...client libraries don’t support promises at the time of writing, so we use pify to handle the conversion of method signatures."

Per your suggestion I made the following modifications -->

```js
exports.initWatch = async (req, res) => {
  // Require a valid email address
  if (!req.query.emailAddress) {
    return res.status(400).send('No emailAddress specified.');
  }
  const email = querystring.unescape(req.query.emailAddress);
  if (!email.includes('@')) {
    return res.status(400).send('Invalid emailAddress.');
  }
  // Retrieve the stored OAuth 2.0 access token
  try {
    const token = await oauth.fetchToken(email);
    const res = await gmail.users.watch({
      auth: oauth.client,
      userId: 'me',
      requestBody: {
        labelIds: ['INBOX'],
        // Replace with `projects/${PROJECT_ID}/topics/${TOPIC_NAME}`
        topicName: `projects/civil-flash-250501/topics/${config.TOPIC_NAME}`
      }
    });
    res.write(`Watch initialized!`);
    res.status(200).end();
  } catch (err) {
    if (err.message === config.UNKNOWN_USER_MESSAGE) {
      res.redirect('/oauth2init');
    } else {
      console.error(err);
      res.status(500).send('Something went wrong; check the logs.');
    }
  }
};

Unfortunately, I still get the same error-->

 Error: invalid_request
    at new RequestError (/srv/node_modules/googleapis/node_modules/google-auth-library/lib/transporters.js:34:42)
    at Request._callback (/srv/node_modules/googleapis/node_modules/google-auth-library/lib/transporters.js:92:27)
    at Request.self.callback (/srv/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/srv/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/srv/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30) code: 400 }

**Comment by lenyabloko** [comment]
Here is the code I used 
package.json-->

"dependencies": {
    "@google-cloud/datastore": "^1.4.0",
    "@google-cloud/debug-agent": "^2.3.0",
    "@google-cloud/vision": "^0.19.0",
    "axios": "^0.18.0",
    "cheerio": "^1.0.0-rc.2",
    "googleapis": "^23.0.0",
    "nconf": "^0.10.0",
    "pify": "^3.0.0",
    "supertest": "^3.0.0"
  },
  "devDependencies": {
    "@google-cloud/nodejs-repo-tools": "2.1.3",
    "ava": "0.24.0",
    "proxyquire": "1.8.0",
    "sinon": "4.1.3"
  },

oauth.js -->
```js
exports.fetchToken = (emailAddress) => {
  return datastore.get(datastore.key(['oauth2Token', emailAddress]))
    .then((tokens) => {
      const token = tokens[0];

      // Check for new users
      if (!token) {
        throw new Error(config.UNKNOWN_USER_MESSAGE);
      }

      // Validate token
      if (!token.expiry_date || token.expiry_date < Date.now() + 60000) {
        oauth2Client.credentials.refresh_token =
          oauth2Client.credentials.refresh_token || token.refresh_token;
        return new Promise((resolve, reject) => { // Pify and oauth2client don't mix
          oauth2Client.refreshAccessToken((err, response) => {
            if (err) {
              return reject(err);
            }
            return resolve();
          });
        })
          .then(() => {
            return exports.saveToken(emailAddress);
          });
      } else {
        oauth2Client.credentials = token;
        return Promise.resolve();
      }
    });
};

**Comment by bcoe** [comment]
we continue to land new versions of `googleapis`, it would be good for us to get the most minimal of regression tests installed on this.
